# Generated by Django 4.1.4 on 2022-12-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raffle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('link', models.URLField()),
                ('winner', models.URLField()),
                ('time_create', models.DateField(auto_now_add=True)),
                ('time_update', models.DateField(auto_now=True)),
                ('creator', models.CharField(max_length=100)),
            ],
        ),
    ]
