# Generated by Django 4.1.4 on 2022-12-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_raffle_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffle',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
