# Generated by Django 4.1.4 on 2023-01-06 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_alter_raffle_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raffle',
            options={'ordering': ('-time_create',)},
        ),
    ]
