# Generated by Django 4.1.4 on 2023-01-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0008_raffle_is_subscribers_alter_raffle_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='qty_winners',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
