# Generated by Django 4.1.4 on 2023-01-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0009_raffle_qty_winners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffle',
            name='qty_winners',
            field=models.PositiveIntegerField(),
        ),
    ]
