# Generated by Django 4.1.4 on 2023-01-08 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('generator', '0010_alter_raffle_qty_winners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='api_vk_key',
            field=models.CharField(max_length=500, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='client',
            name='paid_up_to',
            field=models.DateField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raffles', to=settings.AUTH_USER_MODEL, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='description',
            field=models.TextField(max_length=500, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='is_subscribers',
            field=models.BooleanField(default=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='link',
            field=models.URLField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='qty_winners',
            field=models.PositiveIntegerField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='slug',
            field=models.SlugField(unique=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='title',
            field=models.CharField(max_length=200, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='winner',
            field=models.TextField(verbose_name=''),
        ),
    ]
