# Generated by Django 4.1.4 on 2023-01-08 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('generator', '0011_alter_client_api_vk_key_alter_client_paid_up_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='api_vk_key',
            field=models.CharField(max_length=500, null=True, verbose_name='Ключ VK API'),
        ),
        migrations.AlterField(
            model_name='client',
            name='paid_up_to',
            field=models.DateField(null=True, verbose_name='Оплачено до'),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Введите описание:'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='is_subscribers',
            field=models.BooleanField(default=True, verbose_name='Учитывать только участников группы'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='link',
            field=models.URLField(verbose_name='Введите ссылку на пост Вконтакте:'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='qty_winners',
            field=models.PositiveIntegerField(verbose_name='Введите желаемое количество победителей:'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Введите слаг-адрес:'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания конкурса'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения конкурса'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Введите заголовок:'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='winner',
            field=models.TextField(verbose_name='Победитель'),
        ),
    ]
