# Generated by Django 4.1.4 on 2023-01-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0012_alter_client_api_vk_key_alter_client_paid_up_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='winner_url',
            field=models.TextField(default='text', verbose_name='Ссылка на страницу победителя'),
            preserve_default=False,
        ),
    ]
