# Generated by Django 4.1.4 on 2023-01-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0014_raffle_winner_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='winner_first_name',
            field=models.TextField(default='name', verbose_name='Имя победителя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='raffle',
            name='winner_last_name',
            field=models.TextField(default='familiya', verbose_name='Фамилия победителя'),
            preserve_default=False,
        ),
    ]
