# Generated by Django 4.1.4 on 2023-01-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0015_raffle_winner_first_name_raffle_winner_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffle',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Введите описание:'),
        ),
    ]
