# Generated by Django 4.1.4 on 2023-02-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0017_alter_raffle_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffle',
            name='is_subscribers',
            field=models.BooleanField(verbose_name='Учитывать только участников группы'),
        ),
    ]
