# Generated by Django 4.1.4 on 2023-02-06 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0018_alter_raffle_is_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='display_name',
            field=models.CharField(max_length=120, null=True, verbose_name='Отображаемое имя пользователя'),
        ),
    ]
