# Generated by Django 4.1.4 on 2023-02-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0020_alter_raffle_is_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='display_name',
            field=models.CharField(max_length=120, null=True, verbose_name='Введите новое имя:'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='is_subscribers',
            field=models.BooleanField(verbose_name='Учитывать только участников группы'),
        ),
    ]
